name: Test

on:
  workflow_dispatch:
  
jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    
    steps:
    - name: Find Issue
      uses: actions/github-script@v6
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const opts = github.rest.issues.listForRepo.endpoint.({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              creator: "github-actions",
              title: "Terraform Configuration Drift Detected"
            })
            
            const issues = await github.paginate(opts)
                     
            for (const issue of issues) {
              console.log(issue);
            }

