name: Test

on:
  workflow_dispatch:
  push:
  
jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    
    steps:
    - name: Find Issue
      uses: actions/github-script@v6
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issues = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                creator: 'github-actions[bodt]',
                title: 'Terraform Configuration Drift Detected'
              })
              
            console.log(issues);
            
